pipeline {
    agent { label 'master' }

    options {
      buildDiscarder(logRotator(numToKeepStr: '15'))
    }

    stages {
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }
        stage('Sample Python') {
            steps {
                dir('agents/label/') {
                    sh 'python hello.py'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build successful. Slack notification sent to channel '
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'Build failed. Slack notification sent to channel '
        }
    }
}