pipeline {
    agent any

    parameters {
        string(defaultValue: "none", description: 'Enter Target Server Name', name: 'server_name')
        choice(choices: ['no', 'yes'], description: 'Deploy the code after Testing ?', name: 'deploy_code')
    }

    environment {
      project_name ='normal_pipeline'
    }

    options {
      buildDiscarder(logRotator(numToKeepStr: '16'))
    }    

stages {
        stage('Checkout'){
            steps {
                sh "echo checkout code"
            }
        }

        stage('Build Code'){
            steps {
                sh "echo Project name is ${project_name}"
                sh "echo Enter the Stepts to Build the code"
            }
        }

        stage('Push Code to Testing Environment'){
            steps {
                 echo 'Enter the Stepts to push the code'
            }
        }

        stage('Test the Code'){
            steps {
                 echo 'Enter the Stepts to Test the code'
            }
        }

        stage('Publish code to Production'){
            when {
                allOf {
                    expression { params.deploy_code != 'no' }
                }
            }
            steps {
                 sh "echo Publishing to ${server_name}"
                 echo 'Enter the Stepts to Publish the code'
            }
        }

    }
    post {
        success {
            echo 'Deployment was successful. Sending notification.'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'Build failed. Slack notification.'
        }
    }    
}